export interface InterviewTopic {
  id: string,
  name: string;
  category: string;
  difficulty: string;
  showDescription?: boolean;
}

export const listOfQuestions: InterviewTopic[] = [
  { id: 'debounce-and-throttle', name: 'Debounce and Throttle', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'pure-and-impure-pipe-function', name: 'Pure and impure pipe/function', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'mutability-and-immutability', name: 'Mutability and immutability', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'async-and-defer', name: 'Async and defer', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'cors', name: 'CORS', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'web-performance-optimization', name: 'Web Performance Optimization', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'responsive-web-design', name: 'Responsive Web Design', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'what-is-microfrontend', name: 'What is microfrontend', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'explain-pwa-and-spa', name: 'Explain PWA and SPA', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'pre-processors-scss-or-less', name: 'Pre-processors - SCSS or LESS', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'jwt', name: 'JWT', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'localstorage-sessionstorage', name: 'localStorage/sessionStorage', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'how-to-debug-your-frontend-application', name: 'How to debug your frontend application', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'oops-concepts', name: 'OOPs concepts', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'design-patterns', name: 'Design Patterns', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'what-you-know-about-unit-testing', name: 'What you know about unit testing', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },
  { id: 'understand-different-use-cases-of-the-promises-with-respect-to-api-handling', name: 'Understand different use cases of the Promises with respect to API handling (retry API, combine 2-3 API)', category: 'basicwebquestion', difficulty: 'medium', showDescription: false },

  { id: 'variable-declarations', name: 'Variable Declarations (var, let, const)', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'functions-and-scope', name: 'Functions and Scope', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'closures', name: 'Closures', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'hoisting', name: 'Hoisting', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'currying', name: 'Currying', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'comparison-operators', name: 'comparision-operators', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'array-methods', name: 'array-methods', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'event-loop-callstack-microtask-macrotask', name: 'Event loop (callstack, microtask, macrotask)', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'prototypes-prototype-chain-prototypal-inheritance', name: 'Prototypes, prototype chain, Prototypal Inheritance', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'callback-in-javascript', name: 'Callback in JavaScript', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'asynchronous-javascript-promises-async-await', name: 'Asynchronous JavaScript (Promises, async/await)', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'promise-methods', name: 'Promise methods', category: 'javascript', difficulty: 'medium', showDescription: false },
  { id: 'call-apply-and-bind', name: 'call, apply and bind', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'explain-this-in-javascript', name: 'Explain "this" in JavaScript', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'document-object-model-dom', name: 'Document Object Model (DOM)', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'template-literals-destructuring-spread-operator-rest-operator', name: 'Template literals, Destructuring, Spread Operator, rest operator', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'ES6-feature', name: 'ES6 feature', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'async-and-defer', name: 'Async and defer', category: 'javascript', difficulty: 'medium', showDescription: false },
  { id: 'event-delegation-and-event-propagation', name: 'Event delegation and event propagation ', category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'debounce-and-throttle', name: 'Debounce and Throttle', category: 'javascript', difficulty: 'medium', showDescription: false },
  { id: 'oops-in-javascript', name: 'OOPS in JavaScript', category: 'javascript', difficulty: 'medium', showDescription: false },
  { id: 'design-pattern-in-javscript', name: "Design Pattern in JavaScript", category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'webpack', name: "webpack", category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'deep-copy-shallow-copy', name: "Deep Copy and Shallow Copy", category: 'javascript', difficulty: 'easy', showDescription: false },
  { id: 'frequently-asked-questions', name: 'Frequently Asked Questions', category: 'javascript', difficulty: 'easy', showDescription: false },

  { id: 'angular-workflow', name: 'Angular workflow', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'lifecycle-hooks', name: 'Lifecycle hooks', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'component-communication', name: 'Component communication', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'directives', name: 'Directives (Structural, Attribute and Custom)', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'pipes', name: 'Pipes (Pure, Impure, Built-in)', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'injectable-and-singleton-services', name: 'Injectable and Singleton Services', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'dependency-injection', name: 'Dependency Injection', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'host-listener-and-host-binding', name: 'host listener and host binding', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'one-way-and-two-way-data-binding', name: 'One way and two-way Data Binding', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'route-auth-guards', name: 'Route/Auth Guards', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'lazy-loading', name: 'Lazy loading', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'template-reactive-forms-and-validations', name: 'Template/Reactive Forms and Validations', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'observable-and-promises', name: 'Observable and Promises', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'rxjs-operators', name: 'RXJS Operators', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'subject-and-behavior-subject', name: 'Subject and behavior subject', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'http-interceptor', name: 'HTTP (Req/Res) Interceptor', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'control-value-accessor', name: 'Control value accessor', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'optimization-technique-in-angular', name: 'Optimization technique in Angular', category: 'angular', difficulty: 'medium', showDescription: false},
  { id: 'change-detection-and-onpush', name: 'Change Detection and OnPush', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'dist-and-bundle', name: 'dist and bundle', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'unit-testing-in-angular', name: 'Unit Testing', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'shadow-dom', name: 'Shadow DOM', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'content-projection', name: 'Content projection', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'view-encapsulation', name: 'View Encapsulation', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'ng-deep-and-ng-host', name: 'ng-deep and ng-host', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'angular-signals', name: 'Angular Signals (new reactivity model)', category: 'angular', difficulty: 'advanced', showDescription: false },
  { id: 'standalone-components', name: 'Standalone Components', category: 'angular', difficulty: 'advanced', showDescription: false },
  { id: 'angular-universal', name: 'Angular Universal (Server Side Rendering)', category: 'angular', difficulty: 'advanced', showDescription: false },
  { id: 'angular-elements', name: 'Angular Elements (Web Components)', category: 'angular', difficulty: 'advanced', showDescription: false },
  { id: 'dynamic-component-loading', name: 'Dynamic Component Loading', category: 'angular', difficulty: 'advanced', showDescription: false },
  { id: 'internationalization', name: 'Internationalization (i18n)', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'error-handling', name: 'Error Handling in Angular', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'preloading-strategies', name: 'Preloading Strategies', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'service-workers-pwa', name: 'Service Workers & PWA in Angular', category: 'angular', difficulty: 'advanced', showDescription: false },
  { id: 'custom-validators', name: 'Custom Validators', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'dependency-injection-hierarchy', name: 'Dependency Injection Hierarchy', category: 'angular', difficulty: 'advanced', showDescription: false },
  { id: 'viewchild-contentchild', name: 'ViewChild, ContentChild, ViewChildren, ContentChildren', category: 'angular', difficulty: 'medium', showDescription: false },
  { id: 'angular-security', name: 'Angular Security (XSS, CSRF, DomSanitizer)', category: 'angular', difficulty: 'advanced', showDescription: false },
  { id: 'accessibility', name: 'Accessibility (a11y) in Angular', category: 'angular', difficulty: 'medium', showDescription: false },
];





